### ISSUE TITLE
Crownstone setup mode not available

### ISSUE THREAD

**Issue by giacomo270197** [crownstone/bluenet-python-lib#3]
I am trying to work with a couple brand new Crownstone's (which, as new,  should be in setup mode).
I am able to scan for stones and successfully find them, following is the output:

```
{'address': 'dc:a8:75:df:c5:4f', 'setupMode': False, 'validated': False, 'rssi': -74.4}
```
As the output specifies, the Crownstone is NOT in setup mode.
When I try to reset it, with the following code

```
import sys
import connect_to_stone
from BluenetLib.BLE import BluenetBle


def factory_reset(module):
    module.control.commandFactoryReset()


if __name__ == "__main__":
    ble = BluenetBle(hciIndex=0)
    ble.loadSettingsFromFile("keys.json")
    connect_to_stone.connect_to_stone(ble, sys.argv[1])
    factory_reset(ble)
    ble.disconnect()
    ble.shutDown()
``` 

I get the following error

```
BluenetLib.Exceptions.BluenetBleException: (<BleError.CAN_NOT_FIND_SERVICE: 'CAN_NOT_FIND_SERVICE'>, 'Can not find service: 24f00000-7d10-4805-bfc1-7663a01c3bff')
```

The same service causes problems every time I try to execute a command from the 'Control' module.
Is there a way to put the Crownstone back into setup mode?

**Comment by AlexDM0** [comment]
Hi Giacomo,

Could you try to check if this Crownstone is in setup mode using our consumer smartphone app? The factory reset is only for Crownstones that you have setup yourself. It assumes you have the encryption keys and the command would "disown" the Crownstone.

You can use the consumer app to put the Crownstone back in setup mode. It could also be possible that there is a bug in the Python lib causing them to show up as "not in setup mode". We'll check this now.

Regards

**Comment by giacomo270197** [comment]
Hello,
I did try with the app. The crownstone shows as in setup mode indeed, however I cannot pair with it, an error occurs

**Comment by vliedel** [comment]
Verified.
Parsing seems to go wrong:
`
data {'name': 'Crown', 'rssi': -65, 'address': 'e7:09:62:02:91:3d', 'serviceUUID': 49153, 'serviceData': {'opCode': 6, 'dataType': 21, 'stateOfExternalCrownstone': False, 'hasError': False, 'setupMode': False, 'id': 0, 'switchState': 16, 'flagsBitmask': 184, 'temperature': -109, 'powerFactor': -0.7952755905511811, 'powerUsageReal': 1395.125, 'powerUsageApparent': -1754.2660891089108, 'accumulatedEnergy': -462919582, 'timestamp': -1, 'dimmingAvailable': False, 'dimmingAllowed': False, 'switchLocked': True, 'switchCraftEnabled': False, 'errorMode': False, 'errors': {'overCurrent': False, 'overCurrentDimmer': False, 'temperatureChip': False, 'temperatureDimmer': False, 'dimmerOnFailure': False, 'dimmerOffFailure': False, 'bitMask': 0}, 'uniqueElement': 176, 'timeIsSet': True, 'deviceType': 'PLUG', 'rssiOfExternalCrownstone': 0}}
`

**Comment by vliedel** [comment]
Should be fixed with: 3e9b20ce2e953faf5ad4f92a1672c7a75fc89b7d

**Comment by giacomo270197** [comment]
Indeed, it works now

**Comment by giacomo270197** [comment]
On a different note, I did manage to find one that was not in setup mode, and to set it up. However most of them still figure as not in setup mode when discovered by the python library, but in setup mode when discovered by the mobile app

**Comment by AlexDM0** [comment]
Hi Giacomo,

Could you verify that the consumer app has no firmware updates available for those Crownstones? There has been a protocol change which was introduced before the creation of the python lib. We decided that we would not support deprecated protocols in the python lib.

Regards

**Comment by giacomo270197** [comment]
I see. So the only way I can use the crownstones is to update the firmware manually via the app?
What if the app discovers a stone but throws an error during setup?

**Comment by AlexDM0** [comment]
If this is a recurring problem it could be a hardware fault. Some android phones have a unreliable ble implementation and it could take multiple tries (and resetting the BLE on the phone/the phone itself). We're working on a new android lib that will hopefully fix some of those issues. If you have an iPhone and tried resetting the BLE and / or phone and it still won't work you can send the Crownstone back to us and we will analyse the hardware. If it is a hardware fault we can exchange it for a new one. 
Contact us at team@crownstone.rocks for more information on this.

Regards

**Comment by giacomo270197** [comment]
Alright, thank you for the info
