### ISSUE TITLE
BluenetLib.Exceptions.BluenetBleException: BleError.NO_SESSION_NONCE_SET

### ISSUE THREAD

**Issue by hillstub** [crownstone/bluenet-python-lib#8]
When trying to execute the script `example_switch_crownstone.py` I get the following error:

```
===========================================

Starting Example

===========================================
Connecting to (obfuscated)
Connecting...
Connected
Switch on/off 1
Traceback (most recent call last):
  File "./example_switch_crownstone.py", line 34, in <module>
    core.control.setSwitchState(args.switch)
  File "/usr/local/lib/python3.7/dist-packages/BluenetLib-2.0.0-py3.7.egg/BluenetLib/lib/core/bluenet_modules/ControlHandler.py", line 25, in setSwitchState
  File "/usr/local/lib/python3.7/dist-packages/BluenetLib-2.0.0-py3.7.egg/BluenetLib/lib/core/bluenet_modules/ControlHandler.py", line 160, in _writeControlPacket
  File "/usr/local/lib/python3.7/dist-packages/BluenetLib-2.0.0-py3.7.egg/BluenetLib/lib/core/bluenet_modules/BleHandler.py", line 116, in writeToCharacteristic
  File "/usr/local/lib/python3.7/dist-packages/BluenetLib-2.0.0-py3.7.egg/BluenetLib/lib/util/EncryptionHandler.py", line 164, in encrypt
BluenetLib.Exceptions.BluenetBleException: (<BleError.NO_SESSION_NONCE_SET: 'NO_SESSION_NONCE_SET'>, "Can't Decrypt: No session nonce set")
```

Is there something I have to set before running this script?

**Comment by mrquincle** [comment]
Hi, 

Did you follow the instructions on https://github.com/crownstone/bluenet-python-lib/blob/master/README_BLE.MD? Setting all keys?

```
{
 "admin":  "adminKeyForCrown",
 "member": "memberKeyForHome",
 "basic":  "basicKeyForOther",
 "serviceDataKey":  "MyServiceDataKey",
 "localizationKey":  "aLocalizationKey",
 "meshApplicationKey":  "MyGoodMeshAppKey",
 "meshNetworkKey":  "MyGoodMeshNetKey",
}
```

**Comment by hillstub** [comment]
Yes, all the keys were set.

**Comment by AlexDM0** [comment]
Hi there! We're currently in the process of splitting up the libraries into smaller segments. You can find them here:

https://github.com/crownstone/crownstone-lib-python-core
https://github.com/crownstone/crownstone-lib-python-ble

some of them are on pip at the moment, the BLE one still needs a little work to get it up to speed. The bluenet-python-lib will not receive further updates, all fixes will end up in the cronwstone-lib-python-ble.

I'll update the examples and documentation for you. I'd be happy to hear if the issue is solved using the new library!

Cheers

**Comment by hillstub** [comment]
Hi Alex,
Thanks for your response! I actually started off in the `crownstone-lib-python-ble` repository but then the instruction to `sudo python3 setupBLE.py install` threw me off. Searching for this `setupBLE.py` file led me to this repository ;-).

Enfin, using the proper library indeed helped! Thanks a lot!

Kudos on a great product, btw!!

**Comment by AlexDM0** [comment]
Thanks for the heads up. I updated the documentation.

Cheers
